from .usuario import Usuario as UsuarioResources
from .usuario import Usuarios as UsuariosResources
from .libro import Libro as LibroResources 
from .libro import Libros as LibrosResources
#from .cuenta import Sign_in as Sign_inResources
#from .cuenta import Login as LoginResources
from .prestamo import Prestamo as PrestamoResources
from .prestamo import Prestamos as PrestamosResources
from .valoracion import Valoracion as ValoracionResources
from .autor import Autor as AutorResources
from .autor import Autores as AutoresResources